### ISSUE TITLE
Short Term Todo List

### ISSUE THREAD

**Issue by MiniDigger** [HangarMC/Hangar#1043]
- [x] page change should reload header data (or just call on dropdown of notification/user)
- [x] favicon prod
- [x] error redirect is visible
- [x] https://hangar.papermc.io/ViaVersion is completely broken after having added a member
- [ ] generic nuxt error handling for terminal js errors
- [x] support SVG in image proxy 
- [x] check email templates on auth
- [x] check what's up with case sensitiveness of users and projects 
- [ ] handle large files better (Caused by: io.undertow.server.RequestTooBigException: UT000020: Connection terminated as request was larger than 11534336)
- [x] add TOS, ~privacy policy and other legal shit~
- [x] make textareas nicely resizable 

Auth related
- [x] logout must logout on auth
- [x] control + f5 logs out; same for opening a new tab with a Hangar link
- [x] staying too long on a page also causes token expiry, switching pages after that breaks Hangar
- [x] 2fa alert when 2fa is active already (blocked by https://github.com/ory/kratos/issues/2978)
- [x] Saving project settings works but throws you to a page that errors (probably auth related, with an error message saying you're not logged in) <-- not auth related, pending backend data refactor
- [x] secruity key as first factor
- [ ] Fix changing username

Avatar
- [x] Uploading a project icon: Success message contains response code and body
- [x] Opening the (org) icon upload modal for the first time gives an error that the current avatar could not be fetched
- [x] Org icon uploading broken
