### ISSUE TITLE
graphql todos

### ISSUE THREAD

**Issue by MiniDigger** [HangarMC/Hangar#1280]
```[tasklist]
### Tasks
- [ ] primary key support
- [ ] avatar url for projects needs to fall back to owner I guess
- [ ] expand schema
- [ ] support limits plus set default limit
- [ ] support sorting
- [ ] support filtering
- [ ] Visibility stuff/access control
```
