### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by MiniDigger** [HangarMC/Hangar#335]
# Open ToDos
- [ ] 's can be found in the [Roadmap Project](https://github.com/PaperMC/Hangar/projects/1).' in [CONTRIBUTING.md#4](https://github.com/PaperMC/Hangar/blob/master/CONTRIBUTING.md#L4) <!--CONTRIBUTING.md;4;s can be found in the [Roadmap Project](https://github.com/PaperMC/Hangar/projects/1).-->  
- [ ] 'better waterfall svg?' in [WaterfallLogo.vue#1](https://github.com/PaperMC/Hangar/blob/master/frontend/components/logos/WaterfallLogo.vue#L1) <!--frontend/components/logos/WaterfallLogo.vue;1;better waterfall svg?-->  
- [ ] 'validations for pageContent min/max length from validations state' in [MarkdownEditor.vue#4](https://github.com/PaperMC/Hangar/blob/master/frontend/components/markdown/MarkdownEditor.vue#L4) <!--frontend/components/markdown/MarkdownEditor.vue;4;validations for pageContent min/max length from validations state-->  
- [ ] 'this should be a markdown editor since the reason is rendered in markdown' in [VisibilityChangerModal.vue#13](https://github.com/PaperMC/Hangar/blob/master/frontend/components/modals/VisibilityChangerModal.vue#L13) <!--frontend/components/modals/VisibilityChangerModal.vue;13;this should be a markdown editor since the reason is rendered in markdown-->  
- [ ] 'these should be sorted into somewhat of an order' in [NewPageModal.vue#72](https://github.com/PaperMC/Hangar/blob/master/frontend/components/modals/pages/NewPageModal.vue#L72) <!--frontend/components/modals/pages/NewPageModal.vue;72;these should be sorted into somewhat of an order-->  
- [ ] 'should we confirm the deletion? You are already queuing up the deletion so maybe that's enough' in [MemberList.vue#230](https://github.com/PaperMC/Hangar/blob/master/frontend/components/projects/MemberList.vue#L230) <!--frontend/components/projects/MemberList.vue;230;should we confirm the deletion? You are already queuing up the deletion so maybe that's enough-->  
- [ ] 'other route permissions' in [routePermissions.ts#39](https://github.com/PaperMC/Hangar/blob/master/frontend/middleware/routePermissions.ts#L39) <!--frontend/middleware/routePermissions.ts;39;other route permissions-->  
- [ ] 'get discourse url from backend' in [discuss.vue#46](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/_author/_slug/discuss.vue#L46) <!--frontend/pages/_author/_slug/discuss.vue;46;get discourse url from backend-->  
- [ ] 'origin is null?' in [discuss.vue#130](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/_author/_slug/discuss.vue#L130) <!--frontend/pages/_author/_slug/discuss.vue;130;origin is null?-->  
- [ ] 'download + copy download url' in [index.vue#24](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/_author/_slug/index.vue#L24) <!--frontend/pages/_author/_slug/index.vue;24;download + copy download url-->  
- [ ] 'striped background to separate from normal delete' in [settings.vue#297](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/_author/_slug/settings.vue#L297) <!--frontend/pages/_author/_slug/settings.vue;297;striped background to separate from normal delete-->  
- [ ] 'some way of disabling the reset icon button if not using a custom image' in [settings.vue#572](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/_author/_slug/settings.vue#L572) <!--frontend/pages/_author/_slug/settings.vue;572;some way of disabling the reset icon button if not using a custom image-->  
- [ ] 'implement' in [settings.vue#589](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/_author/_slug/settings.vue#L589) <!--frontend/pages/_author/_slug/settings.vue;589;implement-->  
- [ ] 'this button doesn't seem to show up when the version is restored, you have to reload the page. Unsure why' in [index.vue#50](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/_author/_slug/versions/_version/_platform/index.vue#L50) <!--frontend/pages/_author/_slug/versions/_version/_platform/index.vue;50;this button doesn't seem to show up when the version is restored, you have to reload the page. Unsure why-->  
- [ ] 'route for user action log, with filtering' in [index.vue#67](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/_author/_slug/versions/_version/_platform/index.vue#L67) <!--frontend/pages/_author/_slug/versions/_version/_platform/index.vue;67;route for user action log, with filtering-->  
- [ ] 'validate version string against existing versions. complex because they only have to be unique per-platform' in [new.vue#24](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/_author/_slug/versions/new.vue#L24) <!--frontend/pages/_author/_slug/versions/new.vue;24;validate version string against existing versions. complex because they only have to be unique per-platform-->  
- [ ] 'Implementation</v-alert>' in [health.vue#79](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/admin/health.vue#L79) <!--frontend/pages/admin/health.vue;79;Implementation</v-alert>-->  
- [ ] 'idek what this is for?' in [health.vue#81](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/admin/health.vue#L81) <!--frontend/pages/admin/health.vue;81;idek what this is for?-->  
- [ ] 'figure out a nice way to do filters for AdminLogPage' in [log.vue#85](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/admin/log.vue#L85) <!--frontend/pages/admin/log.vue;85;figure out a nice way to do filters for AdminLogPage-->  
- [ ] 'figure out a way of not having a ton of duplicate code here' in [stats.vue#127](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/admin/stats.vue#L127) <!--frontend/pages/admin/stats.vue;127;figure out a way of not having a ton of duplicate code here-->  
- [ ] 'owner' in [_user.vue#17](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/admin/user/_user.vue#L17) <!--frontend/pages/admin/user/_user.vue;17;owner-->  
- [ ] 'role' in [_user.vue#39](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/admin/user/_user.vue#L39) <!--frontend/pages/admin/user/_user.vue;39;role-->  
- [ ] 'links' in [_user.vue#53](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/admin/user/_user.vue#L53) <!--frontend/pages/admin/user/_user.vue;53;links-->  
- [ ] 'update this once api auth is in' in [api.vue#37](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/api.vue#L37) <!--frontend/pages/api.vue;37;update this once api auth is in-->  
- [ ] 'implement filtering' in [index.vue#77](https://github.com/PaperMC/Hangar/blob/master/frontend/pages/index.vue#L77) <!--frontend/pages/index.vue;77;implement filtering-->  
- [ ] 'hella hacky fix but it fixes the issue reproducible here https://codesandbox.io/s/nuxt-dev-reload-issue-mk16j (also, this only plagues dev env so I guess it doesn't matter?)' in [auth.ts#44](https://github.com/PaperMC/Hangar/blob/master/frontend/plugins/auth.ts#L44) <!--frontend/plugins/auth.ts;44;hella hacky fix but it fixes the issue reproducible here https://codesandbox.io/s/nuxt-dev-reload-issue-mk16j (also, this only plagues dev env so I guess it doesn't matter?)-->  
- [ ] 'fix it complaining about no type declaration file' in [utils.ts#5](https://github.com/PaperMC/Hangar/blob/master/frontend/plugins/utils.ts#L5) <!--frontend/plugins/utils.ts;5;fix it complaining about no type declaration file-->  
- [ ] 'remove or fix' in [utils.ts#7](https://github.com/PaperMC/Hangar/blob/master/frontend/plugins/utils.ts#L7) <!--frontend/plugins/utils.ts;7;remove or fix-->  
- [ ] 'either fix or remove this' in [utils.ts#140](https://github.com/PaperMC/Hangar/blob/master/frontend/plugins/utils.ts#L140) <!--frontend/plugins/utils.ts;140;either fix or remove this-->  
- [ ] 'enum really needed? its just for css styling (at least right now)' in [users.d.ts#12](https://github.com/PaperMC/Hangar/blob/master/frontend/types/internal/users.d.ts#L12) <!--frontend/types/internal/users.d.ts;12;enum really needed? its just for css styling (at least right now)-->  
- [ ] 'this maybe should use the global permissions store in the JWT to reduce db lookups?' in [perms.ts#42](https://github.com/PaperMC/Hangar/blob/master/frontend/utils/perms.ts#L42) <!--frontend/utils/perms.ts;42;this maybe should use the global permissions store in the JWT to reduce db lookups?-->  
- [ ] 'dont need these caches anymore' in [CacheConfig.java#12](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/config/CacheConfig.java#L12) <!--src/main/java/io/papermc/hangar/config/CacheConfig.java;12;dont need these caches anymore-->  
- [ ] 'kinda wack, but idk a better way rn' in [WebConfig.java#75](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/config/WebConfig.java#L75) <!--src/main/java/io/papermc/hangar/config/WebConfig.java;75;kinda wack, but idk a better way rn-->  
- [ ] 'weed out the useless settings' in [SSOConfig.java#12](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/config/hangar/SSOConfig.java#L12) <!--src/main/java/io/papermc/hangar/config/hangar/SSOConfig.java;12;weed out the useless settings-->  
- [ ] 'this doesn't seem to always work... Like it wasn't working (aka it wasn't filtering out fields that the user didn't have permission for) but all I did was add a new line here, and re-built, and it worked. So idk what's up with that.' in [HangarAnnotationIntrospector.java#33](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/config/jackson/HangarAnnotationIntrospector.java#L33) <!--src/main/java/io/papermc/hangar/config/jackson/HangarAnnotationIntrospector.java;33;this doesn't seem to always work... Like it wasn't working (aka it wasn't filtering out fields that the user didn't have permission for) but all I did was add a new line here, and re-built, and it worked. So idk what's up with that.-->  
- [ ] 'all routes pertaining to downloads' in [ApplicationController.java#57](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/controller/ApplicationController.java#L57) <!--src/main/java/io/papermc/hangar/controller/ApplicationController.java;57;all routes pertaining to downloads-->  
- [ ] 'possible versionLog route' in [ApplicationController.java#58](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/controller/ApplicationController.java#L58) <!--src/main/java/io/papermc/hangar/controller/ApplicationController.java;58;possible versionLog route-->  
- [ ] 'needed?' in [LoginController.java#93](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/controller/LoginController.java#L93) <!--src/main/java/io/papermc/hangar/controller/LoginController.java;93;needed?-->  
- [ ] 'implement' in [ApiKeysController.java#20](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/controller/api/v1/ApiKeysController.java#L20) <!--src/main/java/io/papermc/hangar/controller/api/v1/ApiKeysController.java;20;implement-->  
- [ ] 'implement' in [ApiKeysController.java#28](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/controller/api/v1/ApiKeysController.java#L28) <!--src/main/java/io/papermc/hangar/controller/api/v1/ApiKeysController.java;28;implement-->  
- [ ] 'get keys method' in [IApiKeysController.java#38](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/controller/api/v1/interfaces/IApiKeysController.java#L38) <!--src/main/java/io/papermc/hangar/controller/api/v1/interfaces/IApiKeysController.java;38;get keys method-->  
- [ ] 'implement version creation via API' in [IVersionsController.java#30](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/controller/api/v1/interfaces/IVersionsController.java#L30) <!--src/main/java/io/papermc/hangar/controller/api/v1/interfaces/IVersionsController.java;30;implement version creation via API-->  
- [ ] 'remove these bellow eventually' in [RequestPaginationResolver.java#69](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/controller/extras/resolvers/RequestPaginationResolver.java#L69) <!--src/main/java/io/papermc/hangar/controller/extras/resolvers/RequestPaginationResolver.java;69;remove these bellow eventually-->  
- [ ] 'filters/pagination' in [AdminController.java#106](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/controller/internal/admin/AdminController.java#L106) <!--src/main/java/io/papermc/hangar/controller/internal/admin/AdminController.java;106;filters/pagination-->  
- [ ] 'yes, I do think we need to query this. This is public API, and it'd be wrong to just not include it here.' in [ProjectsApiDAO.java#152](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/db/dao/v1/ProjectsApiDAO.java#L152) <!--src/main/java/io/papermc/hangar/db/dao/v1/ProjectsApiDAO.java;152;yes, I do think we need to query this. This is public API, and it'd be wrong to just not include it here.-->  
- [ ] 'yes, I do think we need to query this. This is public API, and it'd be wrong to just not include it here.' in [ProjectsApiDAO.java#178](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/db/dao/v1/ProjectsApiDAO.java#L178) <!--src/main/java/io/papermc/hangar/db/dao/v1/ProjectsApiDAO.java;178;yes, I do think we need to query this. This is public API, and it'd be wrong to just not include it here.-->  
- [ ] 'this might be totally screwed up by adding the platform check' in [VersionsApiDAO.java#183](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/db/dao/v1/VersionsApiDAO.java#L183) <!--src/main/java/io/papermc/hangar/db/dao/v1/VersionsApiDAO.java;183;this might be totally screwed up by adding the platform check-->  
- [ ] 'CompactVersion w/o dependencies for the version list page' in [Version.java#20](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/model/api/project/version/Version.java#L20) <!--src/main/java/io/papermc/hangar/model/api/project/version/Version.java;20;CompactVersion w/o dependencies for the version list page-->  
- [ ] 'remove a bunch of these setters and use a SettingsSave object or smth' in [ProjectTable.java#121](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/model/db/projects/ProjectTable.java#L121) <!--src/main/java/io/papermc/hangar/model/db/projects/ProjectTable.java;121;remove a bunch of these setters and use a SettingsSave object or smth-->  
- [ ] 'deployment key uses this as well' in [LogAction.java#24](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/model/internal/logs/LogAction.java#L24) <!--src/main/java/io/papermc/hangar/model/internal/logs/LogAction.java;24;deployment key uses this as well-->  
- [ ] 'create organization' in [LogAction.java#66](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/model/internal/logs/LogAction.java#L66) <!--src/main/java/io/papermc/hangar/model/internal/logs/LogAction.java;66;create organization-->  
- [ ] 'maybe need the platform in here eventually?' in [LogVersion.java#8](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/model/internal/logs/viewmodels/LogVersion.java#L8) <!--src/main/java/io/papermc/hangar/model/internal/logs/viewmodels/LogVersion.java;8;maybe need the platform in here eventually?-->  
- [ ] 'debug logging' in [PermissionRequiredVoter.java#32](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/security/annotations/permission/PermissionRequiredVoter.java#L32) <!--src/main/java/io/papermc/hangar/security/annotations/permission/PermissionRequiredVoter.java;32;debug logging-->  
- [ ] 'logging' in [PlatformService.java#54](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/service/internal/PlatformService.java#L54) <!--src/main/java/io/papermc/hangar/service/internal/PlatformService.java;54;logging-->  
- [ ] 'logging' in [SSOService.java#87](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/service/internal/auth/SSOService.java#L87) <!--src/main/java/io/papermc/hangar/service/internal/auth/SSOService.java;87;logging-->  
- [ ] 'user's removing themselves from projects/organizations' in [MemberService.java#76](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/service/internal/perms/members/MemberService.java#L76) <!--src/main/java/io/papermc/hangar/service/internal/perms/members/MemberService.java;76;user's removing themselves from projects/organizations-->  
- [ ] 'do we need to enforce unique colors?' in [ChannelService.java#52](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/service/internal/projects/ChannelService.java#L52) <!--src/main/java/io/papermc/hangar/service/internal/projects/ChannelService.java;52;do we need to enforce unique colors?-->  
- [ ] 'what settings changed' in [ProjectService.java#162](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/service/internal/projects/ProjectService.java#L162) <!--src/main/java/io/papermc/hangar/service/internal/projects/ProjectService.java;162;what settings changed-->  
- [ ] 'should this disallow? or just reset project visibility to NEW' in [VersionService.java#87](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/service/internal/versions/VersionService.java#L87) <!--src/main/java/io/papermc/hangar/service/internal/versions/VersionService.java;87;should this disallow? or just reset project visibility to NEW-->  
- [ ] 'previously, if this was a recommended version, it would auto assign a new one, but I don't think that's a good idea. easy enough to just set another, no requirement saying there has to be a recommended version' in [VersionService.java#91](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/service/internal/versions/VersionService.java#L91) <!--src/main/java/io/papermc/hangar/service/internal/versions/VersionService.java;91;previously, if this was a recommended version, it would auto assign a new one, but I don't think that's a good idea. easy enough to just set another, no requirement saying there has to be a recommended version-->  
- [ ] 'prod url, lol) for uploading your plugins!"' in [application.yml#62](https://github.com/PaperMC/Hangar/blob/master/src/main/resources/application.yml#L62) <!--src/main/resources/application.yml;62;prod url, lol) for uploading your plugins!"-->

**Comment by MiniDigger** [comment]
1

**Comment by MiniDigger** [comment]
2
